"""Pre-allocated on-policy rollout buffer with Generalized Advantage Estimation (GAE).

Implements the memory storage and return/advantage estimation pipeline for
Proximal Policy Optimization (PPO, Schulman et al., 2017).
"""

from __future__ import annotations

from typing import Generator, Iterator
import numpy as np
import torch


class RolloutBuffer:
    """Experience rollout buffer for on-policy reinforcement learning.

    Stores complete trajectory rollouts of fixed length T steps generated by
    the current actor-critic policy:
      - Observations s_t: sensory feedback from the fly biomechanics.
      - Actions a_t: continuous motor actuation vector for 42 leg joints.
      - Rewards r_t: locomotion progress and stability scalar rewards.
      - State-Values V(s_t): critic baseline value estimates.
      - Action Log-Probs log π(a_t | s_t): probability density of sampled action.
      - Done flags d_t: termination/truncation indicators.

    After completing a rollout, it computes:
      1. Generalized Advantage Estimation (GAE-λ, Schulman et al., 2015):
           δ_t = r_t + γ * V(s_{t+1}) * (1 - d_t) - V(s_t)
           A_t = δ_t + γ * λ * (1 - d_t) * A_{t+1}
      2. Empirical TD(λ) Returns for the critic:
           R_t = A_t + V(s_t)
    """

    def __init__(
        self,
        buffer_size: int,
        obs_dim: int,
        act_dim: int,
        gamma: float = 0.99,
        gae_lambda: float = 0.95,
        device: torch.device | str = "cpu",
    ) -> None:
        """Initialize pre-allocated rollout buffer tensors.

        Args:
            buffer_size: Number of rollout steps to collect per PPO iteration (T).
            obs_dim: Observation vector dimension (e.g. 100).
            act_dim: Action vector dimension (e.g. 42).
            gamma: Discount factor for future rewards γ ∈ [0, 1].
            gae_lambda: GAE bias-variance trade-off factor λ ∈ [0, 1].
            device: Target torch device (CPU or CUDA).
        """
        self.buffer_size = buffer_size
        self.obs_dim = obs_dim
        self.act_dim = act_dim
        self.gamma = gamma
        self.gae_lambda = gae_lambda
        self.device = torch.device(device)

        # Pre-allocate contiguous PyTorch tensors directly on the target device
        self.obs = torch.zeros((buffer_size, obs_dim), dtype=torch.float32, device=self.device)
        self.actions = torch.zeros((buffer_size, act_dim), dtype=torch.float32, device=self.device)
        self.rewards = torch.zeros((buffer_size,), dtype=torch.float32, device=self.device)
        self.values = torch.zeros((buffer_size,), dtype=torch.float32, device=self.device)
        self.log_probs = torch.zeros((buffer_size,), dtype=torch.float32, device=self.device)
        self.dones = torch.zeros((buffer_size,), dtype=torch.float32, device=self.device)

        # Computed post-rollout
        self.advantages = torch.zeros((buffer_size,), dtype=torch.float32, device=self.device)
        self.returns = torch.zeros((buffer_size,), dtype=torch.float32, device=self.device)

        self.ptr: int = 0
        self.full: bool = False

    def reset(self) -> None:
        """Reset the buffer pointer for the next policy rollout iteration."""
        self.ptr = 0
        self.full = False

    def add(
        self,
        obs: np.ndarray | torch.Tensor,
        action: np.ndarray | torch.Tensor,
        reward: float | torch.Tensor,
        value: float | torch.Tensor,
        log_prob: float | torch.Tensor,
        done: bool | float | torch.Tensor,
    ) -> None:
        """Store a single transition step in the buffer.

        Args:
            obs: Observation vector s_t.
            action: Continuous action vector a_t.
            reward: Immediate scalar reward r_t.
            value: Estimated state value V(s_t).
            log_prob: Log probability of the action log π(a_t | s_t).
            done: Termination or truncation flag (True/1.0 if episode ended).

        Raises:
            IndexError: If attempting to add transitions to a full buffer.
        """
        if self.ptr >= self.buffer_size:
            raise IndexError(
                f"RolloutBuffer overflow! Buffer size is {self.buffer_size}, but tried to add at index {self.ptr}. "
                "Call reset() after training update."
            )

        # Helper to convert numpy / scalar to tensor on device
        def _to_tensor(val: np.ndarray | torch.Tensor | float | bool, target_dim: int | None = None) -> torch.Tensor:
            if isinstance(val, torch.Tensor):
                t = val.detach().to(self.device, dtype=torch.float32)
            elif isinstance(val, np.ndarray):
                t = torch.from_numpy(val).to(self.device, dtype=torch.float32)
            else:
                t = torch.tensor(float(val), dtype=torch.float32, device=self.device)

            if target_dim is not None and t.ndim > 1:
                t = t.view(-1)
            return t

        self.obs[self.ptr] = _to_tensor(obs, self.obs_dim)
        self.actions[self.ptr] = _to_tensor(action, self.act_dim)
        self.rewards[self.ptr] = _to_tensor(reward)
        self.values[self.ptr] = _to_tensor(value).view(())
        self.log_probs[self.ptr] = _to_tensor(log_prob).view(())
        self.dones[self.ptr] = _to_tensor(done).view(())

        self.ptr += 1
        if self.ptr == self.buffer_size:
            self.full = True

    def compute_returns_and_advantages(
        self,
        last_value: float | torch.Tensor,
        last_done: bool | float | torch.Tensor = False,
    ) -> None:
        """Compute Generalized Advantage Estimation (GAE-λ) and TD(λ) returns.

        Recursively computes advantages backward from t = T-1 to t = 0:
            δ_t = r_t + γ * V(s_{t+1}) * (1 - d_t) - V(s_t)
            A_t = δ_t + γ * λ * (1 - d_t) * A_{t+1}
            R_t = A_t + V(s_t)

        Args:
            last_value: Estimated value of the final state V(s_T), bootstrapping the return.
            last_done: Done flag of the final state d_T.
        """
        if not self.full and self.ptr < self.buffer_size:
            # If buffer is not full, compute only up to self.ptr
            valid_len = self.ptr
        else:
            valid_len = self.buffer_size

        if isinstance(last_value, torch.Tensor):
            last_val = float(last_value.detach().cpu().item())
        else:
            last_val = float(last_value)

        last_d = float(last_done)
        last_gae_lam = 0.0

        for t in reversed(range(valid_len)):
            if t == valid_len - 1:
                next_non_terminal = 1.0 - last_d
                next_value = last_val
            else:
                next_non_terminal = 1.0 - float(self.dones[t + 1].item())
                next_value = float(self.values[t + 1].item())

            cur_reward = float(self.rewards[t].item())
            cur_value = float(self.values[t].item())

            # Bellman temporal difference residual
            delta = cur_reward + self.gamma * next_value * next_non_terminal - cur_value

            # Exponential decay recursion
            last_gae_lam = delta + self.gamma * self.gae_lambda * next_non_terminal * last_gae_lam
            self.advantages[t] = last_gae_lam

        self.returns[:valid_len] = self.advantages[:valid_len] + self.values[:valid_len]

    def get_generator(
        self,
        batch_size: int,
        normalize_advantages: bool = True,
    ) -> Iterator[dict[str, torch.Tensor]]:
        """Yield mini-batches of transitions shuffled randomly for PPO optimization.

        Args:
            batch_size: Size of mini-batch (e.g. 64 or 128).
            normalize_advantages: Whether to normalize advantages to mean=0, std=1.

        Yields:
            Dictionary containing mini-batch tensors:
              - 'obs': (B, obs_dim)
              - 'actions': (B, act_dim)
              - 'log_probs': (B,)
              - 'advantages': (B,)
              - 'returns': (B,)
              - 'values': (B,)
        """
        total_steps = self.buffer_size if self.full else self.ptr
        if total_steps == 0:
            raise ValueError("Cannot sample from an empty RolloutBuffer!")

        # Clone advantages to prevent modifying the stored values
        adv = self.advantages[:total_steps].clone()
        if normalize_advantages:
            adv_mean = adv.mean()
            adv_std = adv.std(unbiased=False) + 1e-8
            adv = (adv - adv_mean) / adv_std

        # Permute indices randomly
        indices = torch.randperm(total_steps, device=self.device)

        start_idx = 0
        while start_idx < total_steps:
            batch_indices = indices[start_idx : start_idx + batch_size]
            yield {
                "obs": self.obs[batch_indices],
                "actions": self.actions[batch_indices],
                "log_probs": self.log_probs[batch_indices],
                "advantages": adv[batch_indices],
                "returns": self.returns[batch_indices],
                "values": self.values[batch_indices],
            }
            start_idx += batch_size
